version: pythonocc-core-0.17.{build}

environment:
  matrix:
    - PYTHON: "c:\\Miniconda"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_NPY: "18"

    - PYTHON: "c:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "27"
      CONDA_NPY: "18"

    - PYTHON: "c:\\Miniconda3"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"
      CONDA_NPY: "18"

    - PYTHON: "c:\\Miniconda3-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"
      CONDA_NPY: "18"

    - PYTHON: "c:\\Miniconda3"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "18"

    - PYTHON: "c:\\Miniconda3-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "18"

install:
  - ps: |
      $env:PATH = "$env:PYTHON;$env:PYTHON\Scripts;$env:PATH"
  - conda install conda-build=1.20 --yes --quiet
  - conda config --add channels https://conda.anaconda.org/dlr-sc

build_script:
- conda build ci/conda


test_script:
  # Move the conda package into the current directory, to register it
  # as an "artifact" for Appveyor. cmd.exe does't have good globbing, so
  # we'll use a simple python script.
  - python ci\move-conda-package.py

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'